name: Start Sprint

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      # the package installation will only be executed when the
      # requirements-files have changed.
    - run: pip install -r requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        
    - name: Start sprint
      run: python start_sprint.py
      env: 
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        SPRINTS_TABLE_URL: ${{ secrets.SPRINTS_TABLE_URL }}
