name: Start Sprint

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Prepare env variables
      run: |
        export NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}
        export SPRINTS_TABLE_URL=${{ secrets.SPRINTS_TABLE_URL }}
        
    - name: Start sprint
      run: python start_sprint.py
